name: Keep App Alive

on:
  schedule:
    - cron: "3-59/10 * * * *"
  workflow_dispatch:

jobs:
  keep-alive:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render App
        run: |
          echo "Pinging  app..."
          curl --fail --silent --show-error \
            --max-time 60 \
            https://loanapplication-ak2y.onrender.com/health
          echo "app is responding."
